// Application constants
export const TRANSFER_CONSTANTS = {
  COMPLETION_DISPLAY_DURATION_MS: 2000,
  PROGRESS_POLLING_INTERVAL_MS: 1000,
  SMALL_BATCH_THRESHOLD: 10,
  ESTIMATED_MAX_COMPANIES_FOR_TRANSFER_ALL: 50000,
  LARGE_TRANSFER_THRESHOLD: 1000,
  CACHE_TIMEOUT_MS: 5000,
  DEBOUNCE_DELAY_MS: 300,
} as const;
